name: Testing eBPF Program Compatibility Across Kernels with LVH

on:
  workflow_dispatch: # Allows manually triggering the workflow from the GitHub UI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Ensures only the latest run for the same ref is active

jobs:
  test-ebpf:
    runs-on: ubuntu-latest # Runs the job on the latest Ubuntu GitHub-hosted runner
    name: eBPF Load
    strategy:
      fail-fast: false # Continue running all jobs even if one fails
      matrix:
        # List of kernel versions to test against
        # Find available tags here: https://quay.io/repository/lvh-images/kind?tab=tags
        kernel: 
          - "6.6-20250616.013250-amd64"
          - "5.15-20250616.013250-amd64"
          - "5.10-20250610.043823-amd64"
    timeout-minutes: 10 # Max time per job

    steps:
      - run: | 
          # Download a precompiled eBPF object file
          wget --quiet https://github.com/cilium/ebpf/raw/9958a4f58fb4e533201e0a76d6d82eeeaa91434b/examples/cgroup_skb/bpf_bpfel.o 
          ls -lah # List to confirm the file is downloaded

      - name: Provision LVH VMs
        uses: cilium/little-vm-helper@v0.0.23
        with:
          test-name: test-loading
          image: "kind" # Available options: kind, complexity-test, base
          image-version: ${{ matrix.kernel }} # Pull the specific kernel version for testing
          host-mount: . # Mount the current workspace into the VM
          install-dependencies: "true" # Ensure VM has bpftool and necessary packages
          cmd: |
            # Print the kernel version of the test VM
            echo "Kernel Version: "
            uname -a

            echo ""
            cd /host # Move to mounted host directory
            ls -lah # List files to verify access

            echo ""
            # Try loading the eBPF program using bpftool
            sudo bpftool prog load ./bpf_bpfel.o /sys/fs/bpf/test && echo "Test Successful"
