name: LVH Load

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 
  load-vm:
    runs-on: ubuntu-latest
    name: eBPF Load
    strategy:
      fail-fast: false
      matrix:
        # for kernel tags: https://quay.io/repository/lvh-images/kind?tab=tags
        kernel: 
          - "6.6-20250616.013250-amd64"
          - "5.15-20250616.013250-amd64"
          - "5.10-20250610.043823-amd64"
          
    timeout-minutes: 10
    steps:


      - run: | 
          # download the compiled obj 
          wget --quiet https://github.com/cilium/ebpf/raw/refs/heads/main/examples/cgroup_skb/bpf_bpfel.o  
          ls -lah
      
      - name: Provision LVH VMs
        uses: cilium/little-vm-helper@v0.0.23
        with:
          test-name: load-test
          image: "kind"
          image-version: ${{ matrix.kernel }}
          host-mount: .
          install-dependencies: "true"
          cmd: |

            echo "Kernel Version: "
            uname -a

            echo ""
            cd /host
            ls -lah

            echo ""
            sudo bpftool prog load ./bpf_bpfel.o /sys/fs/bpf/test && echo "Load Success"
